Usb: xhci_handshake_check_state > xhci_handshake
Fix build error due to 4.14.289 changes f4a5311dfd1c

drivers/usb/host/xhci-ring.c:383:8: error: implicit declaration of function 'xhci_handshake_check_state' [-Werror,-Wimplicit-function-declaration]
        ret = xhci_handshake_check_state(xhci, &xhci->op_regs->cmd_ring